# Generated by Django 6.0.4 on 2026-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone do aluno (opcional)', max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
