# Generated by Django 4.2.30 on 2026-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_usuario_aluno_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de celular do aluno (opcional)', max_length=15, null=True, verbose_name='Celular'),
        ),
    ]
