# Generated by Django 4.2.30 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_aluno_telefone_aluno_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(help_text='Endereço de email único do aluno', max_length=150, null=True, verbose_name='Email'),
        ),
    ]
