# Generated by Django 4.2.30 on 2026-05-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_remove_grupo_codigo_alter_grupo_periodo'),
        ('projetos', '0002_remove_projeto_link_github_remove_projeto_titulo_and_more'),
        ('alunos', '0004_alter_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AlunoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota do aluno nesse grupo (0 a 10)', max_digits=4, null=True, verbose_name='Nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_grupos', to='alunos.aluno', verbose_name='Aluno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_grupos', to='grupos.grupo', verbose_name='Grupo')),
                ('projeto', models.ForeignKey(blank=True, help_text='Projeto de referência da nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_grupos', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'ordering': ['grupo', 'aluno'],
                'unique_together': {('aluno', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='Grupos aos quais o aluno pertence', related_name='alunos', through='alunos.AlunoGrupo', to='grupos.grupo', verbose_name='Grupos'),
        ),
    ]
