# Generated by Django 4.2.30 on 2026-05-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_remove_grupo_codigo_alter_grupo_periodo'),
        ('alunos', '0005_remove_aluno_grupo_alter_aluno_id_alunogrupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunogrupo',
            options={},
        ),
        migrations.RemoveField(
            model_name='alunogrupo',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='alunogrupo',
            name='projeto',
        ),
        migrations.AlterField(
            model_name='alunogrupo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_grupos', to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='alunogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_grupos', to='grupos.grupo'),
        ),
    ]
