services:
  - type: web
    name: gerenciamento-mvp-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com