# Generated by Django 4.2.30 on 2026-05-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_alter_grupo_options_grupo_codigo_grupo_data_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='link_github',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.CharField(default='Projeto', help_text='Ano do projeto. Ex: 2024', max_length=4, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='mvp',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Mobile', 'Mobile')], default='Frontend', help_text='Tipo de MVP: Frontend, Backend ou Mobile', max_length=20, verbose_name='MVP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default='2024', help_text='Nome do projeto', max_length=150, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Requisitos do projeto (opcional)', null=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default='Ativo', help_text='Descrição detalhada do projeto', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='grupo',
            field=models.ForeignKey(help_text='Grupo responsável pelo projeto', on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='grupos.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', help_text='Status do projeto: Ativo ou Inativo', max_length=10, verbose_name='Status'),
        ),
    ]
