# Generated by Django 4.2.30 on 2026-06-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_projeto_link_github_remove_projeto_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='grupo',
        ),
    ]
