# Generated by Django 6.0.4 on 2026-04-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='authenticat_email_486e08_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='authenticat_usernam_b8ce7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='authenticat_role_cbb733_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
