# Generated by Django 6.0.4 on 2026-04-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(help_text='Identificador único da entrega', primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição detalhada da entrega', verbose_name='Descrição')),
                ('data_entrega', models.DateTimeField(help_text='Data e hora da entrega do projeto', verbose_name='Data de Entrega')),
                ('apresentado', models.BooleanField(default=False, help_text='Define se o projeto foi apresentado', verbose_name='Apresentado')),
                ('link_apresentacao', models.URLField(blank=True, help_text='Link da apresentação do projeto', max_length=500, null=True, verbose_name='Link da Apresentação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('projeto', models.ForeignKey(help_text='Projeto relacionado à entrega', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'ordering': ['-data_entrega'],
                'indexes': [models.Index(fields=['projeto'], name='entregas_en_projeto_bc25fb_idx'), models.Index(fields=['-data_entrega'], name='entregas_en_data_en_e87b45_idx')],
            },
        ),
    ]
