# Generated by Django 4.2.30 on 2026-06-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupo_projeto'),
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entrega',
            name='entregas_en_projeto_bc25fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='entrega',
            name='entregas_en_data_en_e87b45_idx',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='projeto',
        ),
        migrations.AddField(
            model_name='entrega',
            name='comentario_geral',
            field=models.TextField(blank=True, help_text='Comentário do professor sobre a entrega', null=True, verbose_name='Comentário Geral'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_apresentacao',
            field=models.DateField(blank=True, help_text='Data que o grupo apresentou o projeto', null=True, verbose_name='Data de Apresentação'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='grupo',
            field=models.ForeignKey(default=1, help_text='Grupo que realizou a entrega', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='grupos.grupo', verbose_name='Grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrega',
            name='apresentado',
            field=models.BooleanField(default=False, help_text='Se o grupo já apresentou o projeto', verbose_name='Apresentado'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateField(help_text='Data que o grupo entregou o projeto', verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='link_apresentacao',
            field=models.URLField(blank=True, help_text='Link do vídeo ou slides da apresentação', max_length=500, null=True, verbose_name='Link da Apresentação'),
        ),
    ]
