# Generated by Django 6.0.4 on 2026-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        help_text='Identificador único do grupo',
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nome',
                    models.CharField(
                        help_text='Nome do grupo do Grupo',
                        max_length=100,
                        unique=True,
                        verbose_name='Nome',
                    ),
                ),
                (
                    'criado_em',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Data e hora de criação do grupo',
                        verbose_name='Criado em',
                    ),
                ),
                (
                    'atualizado_em',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Data e hora da última atualização',
                        verbose_name='Atualizado em',
                    ),
                ),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
