# Generated by Django 4.2.30 on 2026-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(default='TEMP', help_text='Código único do grupo. Ex: FE-001, BE-002', max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='data',
            field=models.DateField(default='2024-01-01', help_text='Data de início do grupo', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link do repositório do grupo no GitHub', max_length=500, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='mvp',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Mobile', 'Mobile')], default='Frontend', help_text='Tipo de MVP: Frontend, Backend ou Mobile', max_length=20, verbose_name='MVP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='periodo',
            field=models.CharField(choices=[('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre'), ('3º Semestre', '3º Semestre'), ('4º Semestre', '4º Semestre'), ('5º Semestre', '5º Semestre')], default='1º Semestre', help_text='Período letivo do grupo', max_length=20, verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em andamento', help_text='Status do grupo: Em andamento ou Concluído', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(help_text='Nome do grupo', max_length=100, verbose_name='Nome'),
        ),
    ]
