# Generated by Django 4.2.30 on 2026-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_alter_grupo_options_grupo_codigo_grupo_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='periodo',
            field=models.CharField(choices=[('1º Trimestre', '1º Trimestre'), ('2º Trimestre', '2º Trimestre'), ('3º Trimestre', '3º Trimestre'), ('4º Trimestre', '4º Trimestre'), ('5º Trimestre', '5º Trimestre'), ('6º Trimestre', '6º Trimestre'), ('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre'), ('3º Semestre', '3º Semestre'), ('4º Semestre', '4º Semestre'), ('5º Semestre', '5º Semestre')], help_text='Período letivo do grupo', max_length=20, verbose_name='Período'),
        ),
    ]
