# Generated by Django 4.2.30 on 2026-06-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_projeto_grupo'),
        ('grupos', '0003_remove_grupo_codigo_alter_grupo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto que o grupo está desenvolvendo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='projetos.projeto', verbose_name='Projeto'),
        ),
    ]
